name: "\U0001F41E Bug report"
description: Create a report to help me improve the library
title: Am I a bug or a feature?
labels: [triage, bug]
assignees:
  - alvarosaburido
body:
  - type: markdown
    attributes:
      value: |
        "Thanks for taking the time to fill out this bug report!
        Please consider that I'm maintaining this library on my free time, thanks!"
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the library are you using?
      options:
        - 3.x.x (Vue 3.x)
        - 2 (Vue 2.x - legacy)
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
    - type: textarea
    id: reproduction
    attributes:
      label: Describe the bug
      description: Steps to reproduce the behavior,
    validations:
      required: true
   - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Expected behavior
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages @asigloo/vue-dynamic-forms --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
 - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [docs](https://vue-dynamic-forms-docs.netlify.app/).
          required: true
        - label: Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true