name: Release
on:
  push:
    branches:
      - main
      - next
jobs:
  release:
    name: Run test and Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build Library
        run: yarn build
      - name: Build Types Declarations
        run: yarn build:dts
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
        run: yarn semantic-release
